### ISSUE TITLE
Fix layout

### ISSUE THREAD

**Issue by skodapetr** [cusbg/prankweb#112]
There are scroll bars in the sequence section, they should not be there.

![image](https://user-images.githubusercontent.com/3341693/197149836-0b4a021c-c18f-4d5d-a0a0-964e7577f573.png)

**Comment by luk27official** [comment]
Unfortunately, this is the best way how the RCSB plugin could be visualised right now.
The x-overflow is present because of possible resizing of the entire window (otherwise the whole component would have to be re-rendered, which would be inefficient).
It is possible to reduce the need of the y-overflow by resizing the height of the tracks, but I think that making the tracks smaller would make them less usable.

One improvement that came into my mind was to possibly create a better-looking custom scrollbar.

**Comment by luk27official** [comment]
Moreover, we should try to make the left padding of the track labels smaller, if possible.
