### ISSUE TITLE
User Interface Performance 

### ISSUE THREAD

**Issue by skodapetr** [cusbg/prankweb#113]
When hovering over the sequence view it is not particularly responsive, I move mouse in a medium speed and the line has hard time to cough up. Should we address this issue? Can we address this issue?

**Comment by luk27official** [comment]
On high-end computers the hovering should not be as irresponsive and seems fine to me. It may be slower on laptops, though. 

The only method that is currently invoked by the hover is highlighting the residue in the Mol* viewer.

Maybe it would be better not to instantly try to highlight the current residue, instead, we may wait a few (milli)seconds to invoke the Mol* method when not moving, so fast hovering would just highlight in the RCSB viewer but not in Mol* instantly? Otherwise I cannot think of a way to improve right now.

**Comment by skodapetr** [comment]
So this is called on every mousemove event?

**Comment by luk27official** [comment]
The RCSB interface provides an option to implement a callback which gets invoked every time user hovers over different residue in the viewer. We might leave it empty and not highlight anything at all (which would very likely solve the issue), but that would remove the current functionality.

https://github.com/cusbg/prankweb/blob/d4b4434af38200345507c0e5f578e9d1dab6a318/frontend/client/viewer/rcsb-visualise.ts#L15-L22

https://github.com/cusbg/prankweb/blob/d4b4434af38200345507c0e5f578e9d1dab6a318/frontend/client/viewer/rcsb-visualise.ts#L78-L94
