### ISSUE TITLE
Different prediction results for alphafold structures

### ISSUE THREAD

**Issue by AlexLam37** [cusbg/prankweb#142]
Pocket probability is different if i input through "Predicted structure" (Alphafold uniprot ID) vs if I download the Alphafold structure off uniprot and running on "Custom structure"

For example if I input A0A644EZV9 into Predicted structure I get a pocket probability that I expect
![Screen Shot 2024-04-05 at 12 36 16 pm](https://github.com/cusbg/prankweb/assets/166084931/2ee2f77f-3cf3-45c7-8d0f-4e9187738529)
But if I download the A0A644EZV9 alphafold structure off uniprot and upload that as a "Custom structure" I get different results?
![Screen Shot 2024-04-05 at 12 38 56 pm](https://github.com/cusbg/prankweb/assets/166084931/d2a67ee7-4b30-48a0-b732-a7acd895f193)

Any help would be great as I intend to use the standalone p2rank to perform many predictions, but it seems that p2rank performance for my downloaded structures are not as good as I expect?

**Comment by davidhoksza** [comment]
Thanks for reporting this @AlexLam37 ! 

The problem is that PrankWeb has two different models, one for X-ray structures and one for AF structures. The reason is, that when predicting binding sites from X-ray structures, we use the atoms' b-factors as one of the features. However, AF models use the b-factor field to store information about prediction confidence. Therefore, we have a separate model that does not use the b-factor field and this model is used for AF structures. That is the reason we have two models. 

Now, when the user chooses to use a predicted structure, the server knows it is an AF structure and forces P2Rank (the backend tool that serves PrankWeb with predictions) to use the appropriate model. But when you upload the structure, there is no way to find out that it is actually a CIF file with an AF model, and the server by default uses the default model which uses the b-factor field as one of the features. Which is wrong in this case, because the values in the b-factor field are not b-factors and this can lead to wrong predictions. Anyway, the reason why you are seeing different predictions is that two different models are used.

Currently, there is no direct solution. We are considering enabling the user to specify whether he or she is uploading an AF model when using the "Custom structure" feature. But it will take a week or so.

**Comment by rdk** [comment]
Actually it's [this one](https://github.com/rdk/p2rank/blob/master/distro/config/alphafold.groovy) from distro dir which gets packed into the release tar.gz.

You can use it like this: `prank predict -c alphafold ...`

**Comment by AlexLam37** [comment]
Thank you,

I did in fact run prank predict -c alphafold. however for the example above, it did not match either prankweb scores (see below). I also tried running -c alphafold_conservation_hmm but the scores were lower than that of -c alphafold

![image](https://github.com/cusbg/prankweb/assets/166084931/82716930-e23f-4cc3-aa78-b1f630fb3c9b)
